steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'us-central1-docker.pkg.dev/gen-lang-client-0479297407/orpheus-repo/orpheus-frontend:latest',
            '-f', 'Dockerfile.cpu', # Specify the Dockerfile name here
            '.'
        ]
images:
- 'us-central1-docker.pkg.dev/gen-lang-client-0479297407/orpheus-repo/orpheus-frontend:latest'